services:
  app:
    build:
      context: ./
      dockerfile: ./netanalizer-app-docker/Dockerfile
    container_name: net-analyzer
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
    volumes:
      - ./:/app
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: netanalyzer

    volumes:
        - ./mongodb-docker/mongo-data:/data/db
        - ./mongodb-docker/mongo-seed/ini_scripts:/docker-entrypoint-initdb.d
        - ./mongodb-docker/mongo-seed/01_import_dataset.sh:/docker-entrypoint-initdb.d/01_import_dataset.sh
        - ./mongodb-docker/mongo-seed/dataset.json:/data/dataset.json
    
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: 0
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
